/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Usuario
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsocio = new javax.swing.JButton();
        btnhistorial = new javax.swing.JButton();
        btnentrenamiento = new javax.swing.JButton();
        btnhorario = new javax.swing.JButton();
        btnfisioterapia = new javax.swing.JButton();
        btncuota = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        btnentrenamiento1 = new javax.swing.JButton();
        btnentrenamiento2 = new javax.swing.JButton();
        menusalir = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));
        setName("Menu"); // NOI18N

        btnsocio.setBackground(new java.awt.Color(255, 102, 51));
        btnsocio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsocio.setForeground(new java.awt.Color(0, 0, 204));
        btnsocio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/socio.png"))); // NOI18N
        btnsocio.setMnemonic('S');
        btnsocio.setText("Socio");
        btnsocio.setBorder(new javax.swing.border.MatteBorder(null));
        btnsocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsocioActionPerformed(evt);
            }
        });

        btnhistorial.setBackground(new java.awt.Color(255, 102, 51));
        btnhistorial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnhistorial.setForeground(new java.awt.Color(0, 0, 255));
        btnhistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar historial.png"))); // NOI18N
        btnhistorial.setMnemonic('H');
        btnhistorial.setText("Informes");
        btnhistorial.setBorder(new javax.swing.border.MatteBorder(null));
        btnhistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhistorialActionPerformed(evt);
            }
        });

        btnentrenamiento.setBackground(new java.awt.Color(255, 102, 51));
        btnentrenamiento.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnentrenamiento.setForeground(new java.awt.Color(0, 0, 204));
        btnentrenamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gim_1.png"))); // NOI18N
        btnentrenamiento.setMnemonic('E');
        btnentrenamiento.setText("Entrenamiento");
        btnentrenamiento.setBorder(new javax.swing.border.MatteBorder(null));
        btnentrenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentrenamientoActionPerformed(evt);
            }
        });

        btnhorario.setBackground(new java.awt.Color(255, 102, 51));
        btnhorario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnhorario.setForeground(new java.awt.Color(0, 0, 204));
        btnhorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/horario 1.png"))); // NOI18N
        btnhorario.setMnemonic('H');
        btnhorario.setText("Horario");
        btnhorario.setBorder(new javax.swing.border.MatteBorder(null));
        btnhorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhorarioActionPerformed(evt);
            }
        });

        btnfisioterapia.setBackground(new java.awt.Color(255, 102, 51));
        btnfisioterapia.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnfisioterapia.setForeground(new java.awt.Color(0, 0, 204));
        btnfisioterapia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fisioterapia.png"))); // NOI18N
        btnfisioterapia.setMnemonic('F');
        btnfisioterapia.setText("Fisioterapia");
        btnfisioterapia.setBorder(new javax.swing.border.MatteBorder(null));
        btnfisioterapia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfisioterapiaActionPerformed(evt);
            }
        });

        btncuota.setBackground(new java.awt.Color(255, 102, 51));
        btncuota.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncuota.setForeground(new java.awt.Color(0, 0, 204));
        btncuota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cuota.png"))); // NOI18N
        btncuota.setMnemonic('C');
        btncuota.setText("Cuota");
        btncuota.setBorder(new javax.swing.border.MatteBorder(null));
        btncuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncuotaActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caratula gim.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnentrenamiento1.setBackground(new java.awt.Color(255, 102, 51));
        btnentrenamiento1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnentrenamiento1.setForeground(new java.awt.Color(0, 0, 204));
        btnentrenamiento1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/factura 1.png"))); // NOI18N
        btnentrenamiento1.setMnemonic('F');
        btnentrenamiento1.setText("Factura");
        btnentrenamiento1.setBorder(new javax.swing.border.MatteBorder(null));
        btnentrenamiento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentrenamiento1ActionPerformed(evt);
            }
        });

        btnentrenamiento2.setBackground(new java.awt.Color(255, 102, 51));
        btnentrenamiento2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnentrenamiento2.setForeground(new java.awt.Color(0, 0, 204));
        btnentrenamiento2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asistencia.png"))); // NOI18N
        btnentrenamiento2.setMnemonic('A');
        btnentrenamiento2.setText("Asistencia");
        btnentrenamiento2.setBorder(new javax.swing.border.MatteBorder(null));
        btnentrenamiento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentrenamiento2ActionPerformed(evt);
            }
        });
        setJMenuBar(menusalir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnhistorial, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(btnhorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnentrenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnfisioterapia, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnentrenamiento1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsocio, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnentrenamiento2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncuota, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnhistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btncuota, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnfisioterapia, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnhorario, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsocio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnentrenamiento1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnentrenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnentrenamiento2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(299, 299, 299)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(768, 463));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsocioActionPerformed
Socio frm=new Socio();
        frm.setVisible(true);
        frm.toFront(); 

     
// TODO add your handling code here:
    }//GEN-LAST:event_btnsocioActionPerformed

    private void btnhistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhistorialActionPerformed

    private void btnentrenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentrenamientoActionPerformed
Entrenamiento frm=new Entrenamiento();
        frm.setVisible(true);
        frm.toFront(); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnentrenamientoActionPerformed

    private void btnhorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhorarioActionPerformed
    Horario frm=new Horario();
        frm.setVisible(true);
        frm.toFront();    // TODO add your handling code here:
    }//GEN-LAST:event_btnhorarioActionPerformed

    private void btncuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncuotaActionPerformed
 Cuota frm=new Cuota();
        frm.setVisible(true);
        frm.toFront();   
        // TODO add your handling code here:
    }//GEN-LAST:event_btncuotaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
System.exit(WIDTH);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnentrenamiento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentrenamiento1ActionPerformed
Factura frm=new Factura();
        frm.setVisible(true);
        frm.toFront();           // TODO add your handling code here:
    }//GEN-LAST:event_btnentrenamiento1ActionPerformed

    private void btnentrenamiento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentrenamiento2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnentrenamiento2ActionPerformed

    private void btnfisioterapiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfisioterapiaActionPerformed
Fisioterapia frm=new Fisioterapia();
        frm.setVisible(true);
        frm.toFront(); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnfisioterapiaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Menu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncuota;
    private javax.swing.JButton btnentrenamiento;
    private javax.swing.JButton btnentrenamiento1;
    private javax.swing.JButton btnentrenamiento2;
    private javax.swing.JButton btnfisioterapia;
    private javax.swing.JButton btnhistorial;
    private javax.swing.JButton btnhorario;
    private javax.swing.JButton btnsocio;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menusalir;
    // End of variables declaration//GEN-END:variables
}
